TRANSLATIONS = {
    "en": {
        "name": "English",
        "flag": "🇬🇧",
        "nav_tasks": "My Tasks",
        "nav_add": "Add Task",
        "nav_history": "History",
        "nav_account": "Account",
        "nav_change_password": "Change Password",
        "nav_logout": "Log Out",
        "title_portfolio": "My Tasks",
        "btn_new_task": "New Task",
        "label_pending": "Pending",
        "label_completed": "Completed",
        "filter_all_categories": "All Categories",
        "filter_all_priorities": "All Priorities",
        "priority_high": "HIGH",
        "priority_medium": "MEDIUM",
        "priority_low": "LOW",
        "no_tasks": "No pending tasks.",
        "no_tasks_link": "Add one!",
        "title_new_task": "New Task",
        "title_edit_task": "Edit Task",
        "label_title": "Title",
        "label_description": "Description",
        "label_category": "Category",
        "label_priority": "Priority",
        "label_due_date": "Due Date",
        "placeholder_title": "What needs to be done?",
        "placeholder_description": "Optional details...",
        "placeholder_category": "e.g. Work, Personal",
        "btn_add_task": "Add Task",
        "btn_save": "Save Changes",
        "btn_cancel": "Cancel",
        "title_history": "Completed Tasks",
        "col_title": "Title",
        "col_category": "Category",
        "col_priority": "Priority",
        "col_completed": "Completed",
        "no_history": "No completed tasks yet. Get to work!",
        "title_login": "Log In",
        "title_register": "Register",
        "label_username": "Username",
        "label_password": "Password",
        "label_confirm_password": "Confirm Password",
        "btn_login": "Log In",
        "btn_register": "Create Account",
        "login_no_account": "No account?",
        "register_have_account": "Already have an account?",
        "title_change_password": "Change Password",
        "label_current_password": "Current Password",
        "label_new_password": "New Password",
        "label_confirm_new": "Confirm New Password",
        "btn_change_password": "Change Password",
        "flash_task_added": "Task added!",
        "flash_task_updated": "Task updated!",
        "flash_task_completed": "Task completed!",
        "flash_task_deleted": "Task deleted.",
        "flash_registered": "Registered successfully!",
        "flash_password_changed": "Password changed successfully!",
        "err_title_required": "Task title is required",
        "err_invalid_priority": "Invalid priority",
        "err_username_required": "Username required",
        "err_password_required": "Password required",
        "err_passwords_no_match": "Passwords do not match",
        "err_username_exists": "Username already exists",
        "err_invalid_login": "Invalid username and/or password",
        "err_task_not_found": "Task not found",
        "err_current_password": "Current password incorrect",
        "err_new_password_required": "New password required",
        "language": "Language",
    },
    "es": {
        "name": "Español",
        "flag": "🇪🇸",
        "nav_tasks": "Mis Tareas",
        "nav_add": "Añadir Tarea",
        "nav_history": "Historial",
        "nav_account": "Cuenta",
        "nav_change_password": "Cambiar Contraseña",
        "nav_logout": "Cerrar Sesión",
        "title_portfolio": "Mis Tareas",
        "btn_new_task": "Nueva Tarea",
        "label_pending": "Pendientes",
        "label_completed": "Completadas",
        "filter_all_categories": "Todas las Categorías",
        "filter_all_priorities": "Todas las Prioridades",
        "priority_high": "ALTA",
        "priority_medium": "MEDIA",
        "priority_low": "BAJA",
        "no_tasks": "No hay tareas pendientes.",
        "no_tasks_link": "¡Añade una!",
        "title_new_task": "Nueva Tarea",
        "title_edit_task": "Editar Tarea",
        "label_title": "Título",
        "label_description": "Descripción",
        "label_category": "Categoría",
        "label_priority": "Prioridad",
        "label_due_date": "Fecha Límite",
        "placeholder_title": "¿Qué hay que hacer?",
        "placeholder_description": "Detalles opcionales...",
        "placeholder_category": "ej. Trabajo, Personal",
        "btn_add_task": "Añadir Tarea",
        "btn_save": "Guardar Cambios",
        "btn_cancel": "Cancelar",
        "title_history": "Tareas Completadas",
        "col_title": "Título",
        "col_category": "Categoría",
        "col_priority": "Prioridad",
        "col_completed": "Completada",
        "no_history": "Aún no hay tareas completadas. ¡A trabajar!",
        "title_login": "Iniciar Sesión",
        "title_register": "Registrarse",
        "label_username": "Usuario",
        "label_password": "Contraseña",
        "label_confirm_password": "Confirmar Contraseña",
        "btn_login": "Iniciar Sesión",
        "btn_register": "Crear Cuenta",
        "login_no_account": "¿No tienes cuenta?",
        "register_have_account": "¿Ya tienes cuenta?",
        "title_change_password": "Cambiar Contraseña",
        "label_current_password": "Contraseña Actual",
        "label_new_password": "Nueva Contraseña",
        "label_confirm_new": "Confirmar Nueva Contraseña",
        "btn_change_password": "Cambiar Contraseña",
        "flash_task_added": "¡Tarea añadida!",
        "flash_task_updated": "¡Tarea actualizada!",
        "flash_task_completed": "¡Tarea completada!",
        "flash_task_deleted": "Tarea eliminada.",
        "flash_registered": "¡Registrado con éxito!",
        "flash_password_changed": "¡Contraseña cambiada con éxito!",
        "err_title_required": "El título es obligatorio",
        "err_invalid_priority": "Prioridad inválida",
        "err_username_required": "Usuario requerido",
        "err_password_required": "Contraseña requerida",
        "err_passwords_no_match": "Las contraseñas no coinciden",
        "err_username_exists": "El usuario ya existe",
        "err_invalid_login": "Usuario y/o contraseña incorrectos",
        "err_task_not_found": "Tarea no encontrada",
        "err_current_password": "Contraseña actual incorrecta",
        "err_new_password_required": "Nueva contraseña requerida",
        "language": "Idioma",
    },
    "fr": {
        "name": "Français",
        "flag": "🇫🇷",
        "nav_tasks": "Mes Tâches",
        "nav_add": "Ajouter",
        "nav_history": "Historique",
        "nav_account": "Compte",
        "nav_change_password": "Changer le mot de passe",
        "nav_logout": "Se déconnecter",
        "title_portfolio": "Mes Tâches",
        "btn_new_task": "Nouvelle Tâche",
        "label_pending": "En attente",
        "label_completed": "Terminées",
        "filter_all_categories": "Toutes les catégories",
        "filter_all_priorities": "Toutes les priorités",
        "priority_high": "HAUTE",
        "priority_medium": "MOYENNE",
        "priority_low": "BASSE",
        "no_tasks": "Aucune tâche en attente.",
        "no_tasks_link": "En ajouter une!",
        "title_new_task": "Nouvelle Tâche",
        "title_edit_task": "Modifier la Tâche",
        "label_title": "Titre",
        "label_description": "Description",
        "label_category": "Catégorie",
        "label_priority": "Priorité",
        "label_due_date": "Date limite",
        "placeholder_title": "Qu'est-ce qui doit être fait?",
        "placeholder_description": "Détails optionnels...",
        "placeholder_category": "ex. Travail, Personnel",
        "btn_add_task": "Ajouter la Tâche",
        "btn_save": "Enregistrer",
        "btn_cancel": "Annuler",
        "title_history": "Tâches terminées",
        "col_title": "Titre",
        "col_category": "Catégorie",
        "col_priority": "Priorité",
        "col_completed": "Terminée le",
        "no_history": "Aucune tâche terminée. Au travail!",
        "title_login": "Connexion",
        "title_register": "S'inscrire",
        "label_username": "Nom d'utilisateur",
        "label_password": "Mot de passe",
        "label_confirm_password": "Confirmer le mot de passe",
        "btn_login": "Se connecter",
        "btn_register": "Créer un compte",
        "login_no_account": "Pas de compte?",
        "register_have_account": "Déjà un compte?",
        "title_change_password": "Changer le mot de passe",
        "label_current_password": "Mot de passe actuel",
        "label_new_password": "Nouveau mot de passe",
        "label_confirm_new": "Confirmer le nouveau mot de passe",
        "btn_change_password": "Changer le mot de passe",
        "flash_task_added": "Tâche ajoutée!",
        "flash_task_updated": "Tâche mise à jour!",
        "flash_task_completed": "Tâche terminée!",
        "flash_task_deleted": "Tâche supprimée.",
        "flash_registered": "Inscription réussie!",
        "flash_password_changed": "Mot de passe changé!",
        "err_title_required": "Le titre est requis",
        "err_invalid_priority": "Priorité invalide",
        "err_username_required": "Nom d'utilisateur requis",
        "err_password_required": "Mot de passe requis",
        "err_passwords_no_match": "Les mots de passe ne correspondent pas",
        "err_username_exists": "Nom d'utilisateur déjà pris",
        "err_invalid_login": "Identifiants invalides",
        "err_task_not_found": "Tâche introuvable",
        "err_current_password": "Mot de passe actuel incorrect",
        "err_new_password_required": "Nouveau mot de passe requis",
        "language": "Langue",
    },
    "de": {
        "name": "Deutsch",
        "flag": "🇩🇪",
        "nav_tasks": "Meine Aufgaben",
        "nav_add": "Aufgabe hinzufügen",
        "nav_history": "Verlauf",
        "nav_account": "Konto",
        "nav_change_password": "Passwort ändern",
        "nav_logout": "Abmelden",
        "title_portfolio": "Meine Aufgaben",
        "btn_new_task": "Neue Aufgabe",
        "label_pending": "Ausstehend",
        "label_completed": "Erledigt",
        "filter_all_categories": "Alle Kategorien",
        "filter_all_priorities": "Alle Prioritäten",
        "priority_high": "HOCH",
        "priority_medium": "MITTEL",
        "priority_low": "NIEDRIG",
        "no_tasks": "Keine ausstehenden Aufgaben.",
        "no_tasks_link": "Eine hinzufügen!",
        "title_new_task": "Neue Aufgabe",
        "title_edit_task": "Aufgabe bearbeiten",
        "label_title": "Titel",
        "label_description": "Beschreibung",
        "label_category": "Kategorie",
        "label_priority": "Priorität",
        "label_due_date": "Fälligkeitsdatum",
        "placeholder_title": "Was muss erledigt werden?",
        "placeholder_description": "Optionale Details...",
        "placeholder_category": "z.B. Arbeit, Persönlich",
        "btn_add_task": "Aufgabe hinzufügen",
        "btn_save": "Änderungen speichern",
        "btn_cancel": "Abbrechen",
        "title_history": "Erledigte Aufgaben",
        "col_title": "Titel",
        "col_category": "Kategorie",
        "col_priority": "Priorität",
        "col_completed": "Erledigt am",
        "no_history": "Noch keine erledigten Aufgaben.",
        "title_login": "Anmelden",
        "title_register": "Registrieren",
        "label_username": "Benutzername",
        "label_password": "Passwort",
        "label_confirm_password": "Passwort bestätigen",
        "btn_login": "Anmelden",
        "btn_register": "Konto erstellen",
        "login_no_account": "Kein Konto?",
        "register_have_account": "Bereits ein Konto?",
        "title_change_password": "Passwort ändern",
        "label_current_password": "Aktuelles Passwort",
        "label_new_password": "Neues Passwort",
        "label_confirm_new": "Neues Passwort bestätigen",
        "btn_change_password": "Passwort ändern",
        "flash_task_added": "Aufgabe hinzugefügt!",
        "flash_task_updated": "Aufgabe aktualisiert!",
        "flash_task_completed": "Aufgabe erledigt!",
        "flash_task_deleted": "Aufgabe gelöscht.",
        "flash_registered": "Erfolgreich registriert!",
        "flash_password_changed": "Passwort erfolgreich geändert!",
        "err_title_required": "Titel ist erforderlich",
        "err_invalid_priority": "Ungültige Priorität",
        "err_username_required": "Benutzername erforderlich",
        "err_password_required": "Passwort erforderlich",
        "err_passwords_no_match": "Passwörter stimmen nicht überein",
        "err_username_exists": "Benutzername bereits vergeben",
        "err_invalid_login": "Ungültige Anmeldedaten",
        "err_task_not_found": "Aufgabe nicht gefunden",
        "err_current_password": "Aktuelles Passwort falsch",
        "err_new_password_required": "Neues Passwort erforderlich",
        "language": "Sprache",
    },
    "it": {
        "name": "Italiano",
        "flag": "🇮🇹",
        "nav_tasks": "I miei Compiti",
        "nav_add": "Aggiungi",
        "nav_history": "Cronologia",
        "nav_account": "Account",
        "nav_change_password": "Cambia Password",
        "nav_logout": "Esci",
        "title_portfolio": "I miei Compiti",
        "btn_new_task": "Nuovo Compito",
        "label_pending": "In attesa",
        "label_completed": "Completati",
        "filter_all_categories": "Tutte le categorie",
        "filter_all_priorities": "Tutte le priorità",
        "priority_high": "ALTA",
        "priority_medium": "MEDIA",
        "priority_low": "BASSA",
        "no_tasks": "Nessun compito in attesa.",
        "no_tasks_link": "Aggiungine uno!",
        "title_new_task": "Nuovo Compito",
        "title_edit_task": "Modifica Compito",
        "label_title": "Titolo",
        "label_description": "Descrizione",
        "label_category": "Categoria",
        "label_priority": "Priorità",
        "label_due_date": "Scadenza",
        "placeholder_title": "Cosa deve essere fatto?",
        "placeholder_description": "Dettagli opzionali...",
        "placeholder_category": "es. Lavoro, Personale",
        "btn_add_task": "Aggiungi Compito",
        "btn_save": "Salva Modifiche",
        "btn_cancel": "Annulla",
        "title_history": "Compiti Completati",
        "col_title": "Titolo",
        "col_category": "Categoria",
        "col_priority": "Priorità",
        "col_completed": "Completato il",
        "no_history": "Nessun compito completato. Al lavoro!",
        "title_login": "Accedi",
        "title_register": "Registrati",
        "label_username": "Nome utente",
        "label_password": "Password",
        "label_confirm_password": "Conferma Password",
        "btn_login": "Accedi",
        "btn_register": "Crea Account",
        "login_no_account": "Non hai un account?",
        "register_have_account": "Hai già un account?",
        "title_change_password": "Cambia Password",
        "label_current_password": "Password Attuale",
        "label_new_password": "Nuova Password",
        "label_confirm_new": "Conferma Nuova Password",
        "btn_change_password": "Cambia Password",
        "flash_task_added": "Compito aggiunto!",
        "flash_task_updated": "Compito aggiornato!",
        "flash_task_completed": "Compito completato!",
        "flash_task_deleted": "Compito eliminato.",
        "flash_registered": "Registrazione avvenuta!",
        "flash_password_changed": "Password cambiata!",
        "err_title_required": "Il titolo è obbligatorio",
        "err_invalid_priority": "Priorità non valida",
        "err_username_required": "Nome utente richiesto",
        "err_password_required": "Password richiesta",
        "err_passwords_no_match": "Le password non corrispondono",
        "err_username_exists": "Nome utente già in uso",
        "err_invalid_login": "Credenziali non valide",
        "err_task_not_found": "Compito non trovato",
        "err_current_password": "Password attuale errata",
        "err_new_password_required": "Nuova password richiesta",
        "language": "Lingua",
    },
    "pt": {
        "name": "Português",
        "flag": "🇵🇹",
        "nav_tasks": "Minhas Tarefas",
        "nav_add": "Adicionar",
        "nav_history": "Histórico",
        "nav_account": "Conta",
        "nav_change_password": "Alterar Senha",
        "nav_logout": "Sair",
        "title_portfolio": "Minhas Tarefas",
        "btn_new_task": "Nova Tarefa",
        "label_pending": "Pendentes",
        "label_completed": "Concluídas",
        "filter_all_categories": "Todas as categorias",
        "filter_all_priorities": "Todas as prioridades",
        "priority_high": "ALTA",
        "priority_medium": "MÉDIA",
        "priority_low": "BAIXA",
        "no_tasks": "Nenhuma tarefa pendente.",
        "no_tasks_link": "Adicione uma!",
        "title_new_task": "Nova Tarefa",
        "title_edit_task": "Editar Tarefa",
        "label_title": "Título",
        "label_description": "Descrição",
        "label_category": "Categoria",
        "label_priority": "Prioridade",
        "label_due_date": "Data Limite",
        "placeholder_title": "O que precisa ser feito?",
        "placeholder_description": "Detalhes opcionais...",
        "placeholder_category": "ex. Trabalho, Pessoal",
        "btn_add_task": "Adicionar Tarefa",
        "btn_save": "Salvar Alterações",
        "btn_cancel": "Cancelar",
        "title_history": "Tarefas Concluídas",
        "col_title": "Título",
        "col_category": "Categoria",
        "col_priority": "Prioridade",
        "col_completed": "Concluída em",
        "no_history": "Nenhuma tarefa concluída ainda.",
        "title_login": "Entrar",
        "title_register": "Registrar",
        "label_username": "Nome de usuário",
        "label_password": "Senha",
        "label_confirm_password": "Confirmar Senha",
        "btn_login": "Entrar",
        "btn_register": "Criar Conta",
        "login_no_account": "Não tem conta?",
        "register_have_account": "Já tem uma conta?",
        "title_change_password": "Alterar Senha",
        "label_current_password": "Senha Atual",
        "label_new_password": "Nova Senha",
        "label_confirm_new": "Confirmar Nova Senha",
        "btn_change_password": "Alterar Senha",
        "flash_task_added": "Tarefa adicionada!",
        "flash_task_updated": "Tarefa atualizada!",
        "flash_task_completed": "Tarefa concluída!",
        "flash_task_deleted": "Tarefa excluída.",
        "flash_registered": "Cadastro realizado!",
        "flash_password_changed": "Senha alterada!",
        "err_title_required": "O título é obrigatório",
        "err_invalid_priority": "Prioridade inválida",
        "err_username_required": "Nome de usuário obrigatório",
        "err_password_required": "Senha obrigatória",
        "err_passwords_no_match": "As senhas não coincidem",
        "err_username_exists": "Nome de usuário já existe",
        "err_invalid_login": "Usuário e/ou senha inválidos",
        "err_task_not_found": "Tarefa não encontrada",
        "err_current_password": "Senha atual incorreta",
        "err_new_password_required": "Nova senha obrigatória",
        "language": "Idioma",
    },
    "zh": {
        "name": "中文",
        "flag": "🇨🇳",
        "nav_tasks": "我的任务",
        "nav_add": "添加任务",
        "nav_history": "历史记录",
        "nav_account": "账户",
        "nav_change_password": "修改密码",
        "nav_logout": "退出登录",
        "title_portfolio": "我的任务",
        "btn_new_task": "新建任务",
        "label_pending": "待完成",
        "label_completed": "已完成",
        "filter_all_categories": "所有类别",
        "filter_all_priorities": "所有优先级",
        "priority_high": "高",
        "priority_medium": "中",
        "priority_low": "低",
        "no_tasks": "没有待完成的任务。",
        "no_tasks_link": "添加一个！",
        "title_new_task": "新建任务",
        "title_edit_task": "编辑任务",
        "label_title": "标题",
        "label_description": "描述",
        "label_category": "类别",
        "label_priority": "优先级",
        "label_due_date": "截止日期",
        "placeholder_title": "需要做什么？",
        "placeholder_description": "可选详情...",
        "placeholder_category": "例如：工作、个人",
        "btn_add_task": "添加任务",
        "btn_save": "保存更改",
        "btn_cancel": "取消",
        "title_history": "已完成任务",
        "col_title": "标题",
        "col_category": "类别",
        "col_priority": "优先级",
        "col_completed": "完成时间",
        "no_history": "暂无已完成任务。",
        "title_login": "登录",
        "title_register": "注册",
        "label_username": "用户名",
        "label_password": "密码",
        "label_confirm_password": "确认密码",
        "btn_login": "登录",
        "btn_register": "创建账户",
        "login_no_account": "没有账户？",
        "register_have_account": "已有账户？",
        "title_change_password": "修改密码",
        "label_current_password": "当前密码",
        "label_new_password": "新密码",
        "label_confirm_new": "确认新密码",
        "btn_change_password": "修改密码",
        "flash_task_added": "任务已添加！",
        "flash_task_updated": "任务已更新！",
        "flash_task_completed": "任务已完成！",
        "flash_task_deleted": "任务已删除。",
        "flash_registered": "注册成功！",
        "flash_password_changed": "密码修改成功！",
        "err_title_required": "标题为必填项",
        "err_invalid_priority": "无效的优先级",
        "err_username_required": "用户名为必填项",
        "err_password_required": "密码为必填项",
        "err_passwords_no_match": "两次密码不一致",
        "err_username_exists": "用户名已存在",
        "err_invalid_login": "用户名或密码错误",
        "err_task_not_found": "任务未找到",
        "err_current_password": "当前密码错误",
        "err_new_password_required": "新密码为必填项",
        "language": "语言",
    },
    "ar": {
        "name": "العربية",
        "flag": "🇸🇦",
        "nav_tasks": "مهامي",
        "nav_add": "إضافة مهمة",
        "nav_history": "السجل",
        "nav_account": "الحساب",
        "nav_change_password": "تغيير كلمة المرور",
        "nav_logout": "تسجيل الخروج",
        "title_portfolio": "مهامي",
        "btn_new_task": "مهمة جديدة",
        "label_pending": "معلقة",
        "label_completed": "مكتملة",
        "filter_all_categories": "جميع الفئات",
        "filter_all_priorities": "جميع الأولويات",
        "priority_high": "عالية",
        "priority_medium": "متوسطة",
        "priority_low": "منخفضة",
        "no_tasks": "لا توجد مهام معلقة.",
        "no_tasks_link": "أضف مهمة!",
        "title_new_task": "مهمة جديدة",
        "title_edit_task": "تعديل المهمة",
        "label_title": "العنوان",
        "label_description": "الوصف",
        "label_category": "الفئة",
        "label_priority": "الأولوية",
        "label_due_date": "تاريخ الاستحقاق",
        "placeholder_title": "ما الذي يجب فعله؟",
        "placeholder_description": "تفاصيل اختيارية...",
        "placeholder_category": "مثال: عمل، شخصي",
        "btn_add_task": "إضافة المهمة",
        "btn_save": "حفظ التغييرات",
        "btn_cancel": "إلغاء",
        "title_history": "المهام المكتملة",
        "col_title": "العنوان",
        "col_category": "الفئة",
        "col_priority": "الأولوية",
        "col_completed": "اكتملت في",
        "no_history": "لا توجد مهام مكتملة بعد.",
        "title_login": "تسجيل الدخول",
        "title_register": "إنشاء حساب",
        "label_username": "اسم المستخدم",
        "label_password": "كلمة المرور",
        "label_confirm_password": "تأكيد كلمة المرور",
        "btn_login": "تسجيل الدخول",
        "btn_register": "إنشاء حساب",
        "login_no_account": "ليس لديك حساب؟",
        "register_have_account": "لديك حساب بالفعل؟",
        "title_change_password": "تغيير كلمة المرور",
        "label_current_password": "كلمة المرور الحالية",
        "label_new_password": "كلمة المرور الجديدة",
        "label_confirm_new": "تأكيد كلمة المرور الجديدة",
        "btn_change_password": "تغيير كلمة المرور",
        "flash_task_added": "تمت إضافة المهمة!",
        "flash_task_updated": "تم تحديث المهمة!",
        "flash_task_completed": "تمت المهمة!",
        "flash_task_deleted": "تم حذف المهمة.",
        "flash_registered": "تم التسجيل بنجاح!",
        "flash_password_changed": "تم تغيير كلمة المرور!",
        "err_title_required": "العنوان مطلوب",
        "err_invalid_priority": "أولوية غير صالحة",
        "err_username_required": "اسم المستخدم مطلوب",
        "err_password_required": "كلمة المرور مطلوبة",
        "err_passwords_no_match": "كلمات المرور غير متطابقة",
        "err_username_exists": "اسم المستخدم موجود بالفعل",
        "err_invalid_login": "اسم المستخدم أو كلمة المرور غير صحيحة",
        "err_task_not_found": "المهمة غير موجودة",
        "err_current_password": "كلمة المرور الحالية غير صحيحة",
        "err_new_password_required": "كلمة المرور الجديدة مطلوبة",
        "language": "اللغة",
    },
    "ja": {
        "name": "日本語",
        "flag": "🇯🇵",
        "nav_tasks": "タスク一覧",
        "nav_add": "タスク追加",
        "nav_history": "履歴",
        "nav_account": "アカウント",
        "nav_change_password": "パスワード変更",
        "nav_logout": "ログアウト",
        "title_portfolio": "タスク一覧",
        "btn_new_task": "新しいタスク",
        "label_pending": "未完了",
        "label_completed": "完了済み",
        "filter_all_categories": "すべてのカテゴリ",
        "filter_all_priorities": "すべての優先度",
        "priority_high": "高",
        "priority_medium": "中",
        "priority_low": "低",
        "no_tasks": "未完了のタスクはありません。",
        "no_tasks_link": "追加しましょう！",
        "title_new_task": "新しいタスク",
        "title_edit_task": "タスクを編集",
        "label_title": "タイトル",
        "label_description": "説明",
        "label_category": "カテゴリ",
        "label_priority": "優先度",
        "label_due_date": "期限",
        "placeholder_title": "何をすべきですか？",
        "placeholder_description": "任意の詳細...",
        "placeholder_category": "例：仕事、個人",
        "btn_add_task": "タスクを追加",
        "btn_save": "変更を保存",
        "btn_cancel": "キャンセル",
        "title_history": "完了したタスク",
        "col_title": "タイトル",
        "col_category": "カテゴリ",
        "col_priority": "優先度",
        "col_completed": "完了日時",
        "no_history": "完了したタスクはまだありません。",
        "title_login": "ログイン",
        "title_register": "アカウント登録",
        "label_username": "ユーザー名",
        "label_password": "パスワード",
        "label_confirm_password": "パスワード確認",
        "btn_login": "ログイン",
        "btn_register": "アカウント作成",
        "login_no_account": "アカウントがありませんか？",
        "register_have_account": "すでにアカウントをお持ちですか？",
        "title_change_password": "パスワード変更",
        "label_current_password": "現在のパスワード",
        "label_new_password": "新しいパスワード",
        "label_confirm_new": "新しいパスワードを確認",
        "btn_change_password": "パスワードを変更",
        "flash_task_added": "タスクを追加しました！",
        "flash_task_updated": "タスクを更新しました！",
        "flash_task_completed": "タスクを完了しました！",
        "flash_task_deleted": "タスクを削除しました。",
        "flash_registered": "登録が完了しました！",
        "flash_password_changed": "パスワードを変更しました！",
        "err_title_required": "タイトルは必須です",
        "err_invalid_priority": "無効な優先度",
        "err_username_required": "ユーザー名は必須です",
        "err_password_required": "パスワードは必須です",
        "err_passwords_no_match": "パスワードが一致しません",
        "err_username_exists": "このユーザー名はすでに使用されています",
        "err_invalid_login": "ユーザー名またはパスワードが無効です",
        "err_task_not_found": "タスクが見つかりません",
        "err_current_password": "現在のパスワードが正しくありません",
        "err_new_password_required": "新しいパスワードは必須です",
        "language": "言語",
    },
}

SUPPORTED_LANGUAGES = list(TRANSLATIONS.keys())
DEFAULT_LANGUAGE = "en"


def get_translations(lang):
    return TRANSLATIONS.get(lang, TRANSLATIONS[DEFAULT_LANGUAGE])